const fs = require("fs");
const path = require("path");

const keys = require("./stage-keys.json");

const dynamic = [
  ["propertiesPanel.layerType.text", "Text layer"],
  ["propertiesPanel.layerType.shape", "Shape layer"],
  ["propertiesPanel.layerType.image", "Image layer"],
  ["propertiesPanel.layerType.group", "Group"],
  ["propertiesPanel.layerType.null", "Null controller"],
  ["propertiesPanel.layerType.video", "Video layer"],
  ["propertiesPanel.layerType.composition", "Precomp layer"],
  ["propertiesPanel.layerType.adjustment", "Adjustment layer"],
  ["propertiesPanel.layerType.particle", "Particle layer"],
  ["propertiesPanel.layerType.scene3d", "3D object"],
  ["propertiesPanel.fontWeight.300", "Light"],
  ["propertiesPanel.fontWeight.400", "Regular"],
  ["propertiesPanel.fontWeight.500", "Medium"],
  ["propertiesPanel.fontWeight.600", "Semi Bold"],
  ["propertiesPanel.fontWeight.700", "Bold"],
  ["propertiesPanel.fontWeight.800", "Extra Bold"],
  ["propertiesPanel.fontWeight.900", "Black"],
  ["propertiesPanel.shapeType.rectangle", "Rectangle"],
  ["propertiesPanel.shapeType.circle", "Circle"],
  ["propertiesPanel.shapeType.ellipse", "Ellipse"],
  ["propertiesPanel.shapeType.triangle", "Triangle"],
  ["propertiesPanel.shapeType.star", "Star"],
  ["propertiesPanel.shapeType.path", "Path"],
  ["propertiesPanel.lightType.ambient", "Ambient"],
  ["propertiesPanel.lightType.point", "Point"],
  ["propertiesPanel.lightType.directional", "Directional"],
  ["propertiesPanel.environment.studio", "Studio"],
  ["propertiesPanel.environment.warm", "Warm"],
  ["propertiesPanel.environment.cool", "Cool"],
  ["propertiesPanel.environment.sunset", "Sunset"],
  ["propertiesPanel.environment.city", "City"],
  ["propertiesPanel.environment.dark", "Dark"],
  ["propertiesPanel.environment.none", "None"],
];

const all = [...keys, ...dynamic];

const ZH = {
  "+ Add animator": "+ 添加动画器",
  "0 disables word wrap": "0 表示不自动换行",
  "0 removes stroke": "0 表示无描边",
  "3D object": "3D 对象",
  "Active camera": "激活相机",
  Add: "添加",
  "Add Offset Paths": "添加偏移路径",
  "Add Pucker & Bloat": "添加内陷与膨胀",
  "Add Repeater": "添加重复器",
  "Add Round Corners": "添加圆角",
  "Add Trim Paths": "添加修剪路径",
  "Add Trim Paths, Repeater, Zig Zag, Round Corners, Wiggle Paths, Offset Paths, Pucker & Bloat, or Twist modifiers for logo reveals, line draws, patterns, echoes, kinetic outlines, and organic distortions.":
    "添加修剪路径、重复器、锯齿、圆角、摆动路径、偏移路径、内陷与膨胀或扭转修改器，用于标志显现、线条绘制、图案、回声、动态轮廓和有机变形。",
  "Add Twist": "添加扭转",
  "Add Wiggle Paths": "添加摆动路径",
  "Add Zig Zag": "添加锯齿",
  "Add a text animator for character reveals, type-on effects, kinetic headlines, and staggered title sequences.":
    "为字符显现、打字机效果、动态标题和交错标题序列添加文本动画器。",
  "Add a video from the Assets panel to bind this layer to real footage.":
    "从素材面板添加视频，将此图层绑定到真实素材。",
  "Add an image from the Assets panel to bind this layer to real media.":
    "从素材面板添加图像，将此图层绑定到真实媒体。",
  "Add camera keyframe": "添加相机关键帧",
  "Add keyframe": "添加关键帧",
  "Add light keyframe": "添加灯光关键帧",
  "Add path keyframe": "添加路径关键帧",
  "Add stop": "添加色标",
  "Add text animator preset": "添加文本动画器预设",
  Adjustment: "调整图层",
  "Adjustment layer": "调整图层",
  "Align & Distribute": "对齐与分布",
  "Align bottom": "底对齐",
  "Align horizontal center": "水平居中对齐",
  "Align left": "左对齐",
  "Align right": "右对齐",
  "Align selected layers": "对齐选中图层",
  "Align top": "顶对齐",
  "Align vertical center": "垂直居中对齐",
  Ambient: "环境光",
  Amount: "数量",
  Anchor: "锚点",
  Angle: "角度",
  Animation: "动画",
  Aperture: "光圈",
  Background: "背景",
  "Based on": "基于",
  Bevel: "斜角",
  Black: "黑体",
  "Blend mode": "混合模式",
  Blending: "混合",
  "Blur layers away from the camera focus plane":
    "使远离相机焦平面的图层模糊",
  Bold: "粗体",
  "Box width": "文本框宽度",
  "Built-in": "内置",
  Butt: "平头",
  Camera: "相机",
  "Cast shadow": "投射阴影",
  "Changes apply to all selected, unlocked layers. Animated opacity writes a keyframe at the playhead.":
    "更改将应用于所有已选中且未锁定的图层。动画不透明度会在播放头处写入关键帧。",
  Characters: "字符",
  Circle: "圆形",
  City: "城市",
  "Clear guides": "清除参考线",
  "Clear path keyframes": "清除路径关键帧",
  "Clear remap": "清除重映射",
  "Closed path": "闭合路径",
  Color: "颜色",
  Composition: "合成",
  Contain: "包含",
  Content: "内容",
  Controller: "控制器",
  Cool: "冷色",
  Copies: "副本数",
  "Corner radius": "圆角半径",
  Cover: "覆盖",
  Dark: "暗色",
  "Dash offset": "虚线偏移",
  "Dash pattern": "虚线样式",
  "Delete selection": "删除所选内容",
  Depth: "深度",
  "Depth of field": "景深",
  Detail: "细节",
  Direction: "方向",
  Directional: "平行光",
  "Disable Offset Paths": "禁用偏移路径",
  "Disable Pucker & Bloat": "禁用内陷与膨胀",
  "Disable Repeater": "禁用重复器",
  "Disable Round Corners": "禁用圆角",
  "Disable Text Animator": "禁用文本动画器",
  "Disable Trim Paths": "禁用修剪路径",
  "Disable Twist": "禁用扭转",
  "Disable Wiggle Paths": "禁用摆动路径",
  "Disable Zig Zag": "禁用锯齿",
  "Disable animation": "禁用动画",
  "Disable light": "禁用灯光",
  "Distribute horizontally": "水平分布",
  "Distribute vertically": "垂直分布",
  "Duplicate selection": "复制所选内容",
  Duration: "时长",
  Ease: "缓动",
  "Ease in": "缓入",
  "Ease out": "缓出",
  Ellipse: "椭圆",
  "Enable Offset Paths": "启用偏移路径",
  "Enable Pucker & Bloat": "启用内陷与膨胀",
  "Enable Repeater": "启用重复器",
  "Enable Round Corners": "启用圆角",
  "Enable Text Animator": "启用文本动画器",
  "Enable Trim Paths": "启用修剪路径",
  "Enable Twist": "启用扭转",
  "Enable Wiggle Paths": "启用摆动路径",
  "Enable Zig Zag": "启用锯齿",
  "Enable light": "启用灯光",
  "Enable remap": "启用重映射",
  "Enable shutter blur": "启用快门模糊",
  End: "结束",
  "End color": "结束颜色",
  "End opacity": "结束不透明度",
  Environment: "环境",
  "Extra Bold": "特粗",
  Fill: "填充",
  "Fill color": "填充颜色",
  "Fill mode": "填充模式",
  "Fill opacity": "填充不透明度",
  "Fill previews": "填充预览",
  "Fill type": "填充类型",
  Fit: "适配",
  Focus: "对焦",
  "Font family": "字体",
  "Font weight": "字重",
  Forward: "正向",
  "Frame rate": "帧速率",
  Freeze: "冻结",
  "Freeze frame": "冻结帧",
  "From center": "从中心",
  "Frozen source time": "冻结源时间",
  General: "通用",
  Grad: "渐变",
  "Gradient stroke": "渐变描边",
  "Gradient type": "渐变类型",
  Gravity: "重力",
  Group: "组",
  "Ground shadow": "地面阴影",
  Guide: "参考图层",
  "Guide color": "参考线颜色",
  "Guide orientation": "参考线方向",
  "Guide size": "参考线大小",
  Guides: "参考线",
  "HDRI map URL": "HDRI 贴图 URL",
  Height: "高度",
  "Hide all": "全部隐藏",
  Horizontal: "水平",
  Image: "图像",
  "Image fit": "图像适配",
  "Image layer": "图像图层",
  "Image source": "图像源",
  "Initial X": "初始 X",
  "Initial Y": "初始 Y",
  "Initial opacity": "初始不透明度",
  "Initial rotation": "初始旋转",
  "Initial scale": "初始缩放",
  "Inner radius": "内半径",
  "Instance overrides": "实例覆盖",
  "Key color": "主光颜色",
  "Key intensity": "主光强度",
  "Key time": "记录时间",
  "Layer Options": "图层选项",
  Leading: "行距",
  Lifetime: "生命周期",
  Light: "细体",
  "Light type": "灯光类型",
  "Lighting & Environment": "灯光与环境",
  Lights: "灯光",
  "Line cap": "端点",
  "Line join": "拐角",
  Linear: "线性",
  Lock: "锁定",
  "Lock all": "全部锁定",
  "Loop source": "循环源",
  Max: "最大值",
  "Max blur": "最大模糊",
  Medium: "中等",
  Miter: "尖角",
  "Motion Blur": "运动模糊",
  "Motion blur": "运动模糊",
  "Multi-selection inspector": "多选检查器",
  "Mute audio": "静音",
  Name: "名称",
  "No guides": "无参考线",
  "No lights": "无灯光",
  None: "无",
  "Null controller": "空对象控制器",
  Offset: "偏移",
  Opacity: "不透明度",
  "Opacity (average)": "不透明度（平均值）",
  "Open source composition": "打开源合成",
  "Orient along path": "沿路径定向",
  "Pan, zoom, rotate, and push the whole scene in 3D space":
    "在 3D 空间中平移、缩放、旋转并推拉整个场景",
  Parent: "父级",
  "Particle layer": "粒子图层",
  "Particle shape": "粒子形状",
  Particles: "粒子",
  Path: "路径",
  "Path data": "路径数据",
  "Path morph": "路径变形",
  Perspective: "透视",
  Phase: "相位",
  Playback: "播放速度",
  Point: "点光",
  Points: "点数",
  Position: "位置",
  "Position X": "位置 X",
  "Position Y": "位置 Y",
  Precomp: "预合成",
  "Precomp fit": "预合成适配",
  "Precomp layer": "预合成图层",
  "Preserve 3D": "保持 3D",
  Radial: "径向",
  Radius: "半径",
  Random: "随机",
  Rate: "速率",
  Rectangle: "矩形",
  Regular: "常规",
  Remove: "移除",
  "Remove Offset Paths": "移除偏移路径",
  "Remove Pucker & Bloat": "移除内陷与膨胀",
  "Remove Repeater": "移除重复器",
  "Remove Round Corners": "移除圆角",
  "Remove Text Animator": "移除文本动画器",
  "Remove Trim Paths": "移除修剪路径",
  "Remove Twist": "移除扭转",
  "Remove Wiggle Paths": "移除摆动路径",
  "Remove Zig Zag": "移除锯齿",
  "Remove camera keyframe": "移除相机关键帧",
  "Remove guide": "移除参考线",
  "Remove keyframe": "移除关键帧",
  "Remove light": "移除灯光",
  "Remove light keyframe": "移除灯光关键帧",
  "Remove stop {{index}}": "移除色标 {{index}}",
  Reset: "重置",
  "Reset all": "全部重置",
  "Reset camera": "重置相机",
  Reverse: "反向",
  Ridges: "脊数",
  "Rim intensity": "轮廓光强度",
  Roll: "滚转",
  Rotation: "旋转",
  Round: "圆形",
  Samples: "采样",
  Scale: "缩放",
  "Scale X": "缩放 X",
  "Scale Y": "缩放 Y",
  "Scene name": "场景名称",
  "Scene settings": "场景设置",
  Seed: "随机种子",
  "Select a layer on the stage or in the layers panel to edit its transform, timing, and style.":
    "在舞台或图层面板中选择一个图层，以编辑其变换、时间和样式。",
  "Select option": "选择选项",
  "Selection Actions": "选择操作",
  "Semi Bold": "半粗",
  Shader: "着色器",
  "Shader animator": "着色器动画",
  "Shader fill": "着色器填充",
  Shape: "形状",
  "Shape Modifiers": "形状修改器",
  "Shape layer": "形状图层",
  "Shape type": "形状类型",
  "Shared Appearance": "共享外观",
  "Show all": "全部显示",
  "Show environment as backdrop": "将环境显示为背景",
  "Shutter angle": "快门角度",
  Size: "大小",
  Solid: "纯色",
  "Solid stroke": "纯色描边",
  Solo: "独奏",
  Source: "源",
  "Source composition": "源合成",
  "Source time at playhead": "播放头处的源时间",
  Speed: "速度",
  Spread: "扩散",
  Square: "方形",
  Stagger: "交错",
  Star: "星形",
  Start: "起始",
  "Start color": "起始颜色",
  "Start opacity": "起始不透明度",
  "Start time": "起始时间",
  Stroke: "描边",
  "Stroke color": "描边颜色",
  "Stroke fill": "描边填充",
  "Stroke opacity": "描边不透明度",
  "Stroke reveal modifier": "描边显现修改器",
  "Stroke width": "描边宽度",
  Studio: "影棚",
  Sunset: "日落",
  Text: "文本",
  "Text Animators": "文本动画器",
  "Text layer": "文本图层",
  "Text shader animator": "文本着色器动画",
  "This precomp layer references a composition that is no longer in the project.":
    "此预合成图层引用的合成已不在项目中。",
  "Time offset": "时间偏移",
  "Time remap": "时间重映射",
  Timing: "时间",
  Tracking: "字距",
  Transform: "变换",
  Triangle: "三角形",
  "Trim Start": "修剪起点",
  Type: "类型",
  "Unlock all": "全部解锁",
  "Update key": "更新关键帧",
  "Update path keyframe": "更新路径关键帧",
  Vertical: "垂直",
  Video: "视频",
  "Video fit": "视频适配",
  "Video layer": "视频图层",
  "Video source": "视频源",
  Warm: "暖色",
  Width: "宽度",
  Words: "单词",
  Zoom: "缩放",
  "image-based lighting": "基于图像的光照",
  "{{action}} {{label}} keyframe": "{{action}} {{label}} 关键帧",
  "{{amount}}% distortion": "{{amount}}% 变形",
  "{{amount}}px {{join}} join": "{{amount}}px {{join}} 拐角",
  "{{angle}}deg twist": "{{angle}} 度扭转",
  "{{axis}} value": "{{axis}} 值",
  "{{count}} generated copies": "生成 {{count}} 个副本",
  "{{count}} keys": "{{count}} 个关键帧",
  "{{count}} layers selected": "已选择 {{count}} 个图层",
  "{{count}} ridges per segment": "每段 {{count}} 个脊",
  "{{label}}, {{count}} keys": "{{label}}，{{count}} 个关键帧",
  "{{name}} {{rate}}/s": "{{name}} {{rate}}/s",
  "{{radius}}px radius, {{segments}} samples":
    "半径 {{radius}}px，{{segments}} 个采样",
  "{{size}}px at {{speed}}x speed": "{{size}}px，速度 {{speed}}x",
};

// key-level overrides where the same English literal needs different Chinese
const ZH_OVERRIDE = {
  "propertiesPanel.shape.lineCapRound": "圆头",
  "propertiesPanel.shape.lineJoinRound": "圆角",
  "propertiesPanel.particles.square": "方形",
  "propertiesPanel.shape.lineCapSquare": "方头",
  "propertiesPanel.layerOptions.guideLayer": "参考图层",
  "propertiesPanel.common.start": "起始",
  "propertiesPanel.common.end": "结束",
};

function setDeep(root, dotted, value) {
  const parts = dotted.split(".");
  let node = root;
  for (let i = 0; i < parts.length - 1; i += 1) {
    const part = parts[i];
    if (typeof node[part] === "string") {
      throw new Error("path conflict at " + parts.slice(0, i + 1).join("."));
    }
    if (!node[part]) node[part] = {};
    node = node[part];
  }
  const last = parts[parts.length - 1];
  if (node[last] && typeof node[last] === "object") {
    throw new Error("path conflict at " + dotted);
  }
  if (node[last] !== undefined && node[last] !== value) {
    throw new Error("value conflict at " + dotted);
  }
  node[last] = value;
}

const en = {};
const zh = {};
const missing = [];
for (const [key, def] of all) {
  setDeep(en, key, def);
  let tr = ZH_OVERRIDE[key];
  if (tr === undefined) tr = ZH[def];
  if (tr === undefined) missing.push([key, def]);
  setDeep(zh, key, tr === undefined ? def : tr);
}
if (missing.length) {
  console.log("MISSING ZH:", JSON.stringify(missing, null, 1));
  process.exitCode = 1;
}

const root = path.join(__dirname, "src/i18n/locales");
fs.writeFileSync(
  path.join(root, "en/_stage-a2a.g1.json"),
  JSON.stringify(en, null, 2) + "\n",
  "utf8",
);
fs.writeFileSync(
  path.join(root, "zh-CN/_stage-a2a.g1.json"),
  JSON.stringify(zh, null, 2) + "\n",
  "utf8",
);
console.log("keys written:", all.length);
